# Generated by Django 3.2.6 on 2021-08-23 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('profesor_guia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studentscrud.profesor', verbose_name='Profesor guía')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('ciudad_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studentscrud.ciudad', verbose_name='Ciudad de nacimiento')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='studentscrud.grupo')),
            ],
        ),
    ]
